server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job_queue
    username: queue_user
    password: queue_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  threads:
    virtual:
      enabled: true # Forces Spring to use lightweight Virtual Threads instead of OS threads

logging:
  level:
    root: INFO
    # Only show DEBUG logs for our own code
    com.queue.worker: DEBUG